version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - notes_network

  api:
    build:
      context: ./NotesApi
      dockerfile: Dockerfile
    container_name: notes_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=notesdb;Uid=notesuser;Pwd=notespassword;
    ports:
      - "5197:80"
    depends_on:
      - mysql
    networks:
      - notes_network

volumes:
  mysql_data:

networks:
  notes_network:
    driver: bridge
